# Location of the theme's resources.http_path = "/"
images_dir = "../images"
css_dir         = "../css"
sass_dir        = "."
extensions_dir  = "sass-extensions"
javascripts_dir = "js"
output_style = :compressed
relative_assets=true
line_comments = false